FamilyAccounting.Web/Models/TransactionViewModel.cs
using FamilyAccounting.DAL.Entities;
using System;

namespace FamilyAccounting.Web.Models
{
    public class TransactionViewModel
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int SourceWalletId { get; set; }
        public string SourceWallet { get; set; }
        public int TargetWalletId { get; set; }
        public string TargetWallet { get; set; }
        public string Description { get; set; }
        public DateTime TimeStamp { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public bool State { get; set; }
        public TransactionTypeViewModel TransactionType { get; set; }
        public decimal BalanceBefore { get; set; }
        public decimal BalanceAfter { get; set; }
    }
}

FamilyAccounting.Web/Controllers/TransactionController.cs
using FamilyAccounting.Web.Interfaces;
using FamilyAccounting.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace FamilyAccounting.Web.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionWebService transactionWebService;
        private readonly IWalletWebService walletWebService;

        public TransactionController(ITransactionWebService transactionWebService, IWalletWebService walletWebService)
        {
            this.transactionWebService = transactionWebService;
            this.walletWebService = walletWebService;
        }

        [HttpGet]
        public IActionResult Details(int walletId, int transactionId)
        {
            var transaction = transactionWebService.Get(walletId, transactionId);
            return View(transaction);
        }

        [HttpGet]
        public IActionResult MakeExpense(int id)
        {
            var wallet = walletWebService.Get(id);
            var categories = transactionWebService.GetExpenseCategories();
            var transaction = new TransactionViewModel
            {
                SourceWalletId = (int)wallet.Id,
                SourceWallet = wallet.Description
            };
            ViewBag.Categories = categories;
            return View(transaction);
        }

        [HttpPost]
        public IActionResult MakeExpense(TransactionViewModel transaction)
        {
            transactionWebService.MakeExpense(transaction);
            return RedirectToAction("Details", "Wallet", new
            {
                id = transaction.SourceWalletId
            });
        }

        [HttpGet]
        public IActionResult MakeIncome(int id)
        {
            var wallet = walletWebService.Get(id);
            var categories = transactionWebService.GetIncomeCategories();
            var transaction = new TransactionViewModel
            {
                TargetWalletId = (int)wallet.Id,
                TargetWallet = wallet.Description
            };
            ViewBag.Categories = categories;
            return View(transaction);
        }

        [HttpGet]
        public IActionResult MakeTransfer(int id)
        {
            var wallet = walletWebService.Get(id);
            var transaction = new TransactionViewModel
            {
                SourceWalletId = (int)wallet.Id,
                SourceWallet = wallet.Description,
            };
            var wallets = walletWebService.Get();
            ViewBag.Wallets = wallets;
            return View(transaction);
        }

        [HttpPost]
        public IActionResult MakeIncome(TransactionViewModel transaction)
        {
            transactionWebService.MakeIncome(transaction);
            return RedirectToAction("Details", "Wallet", new
            {
                id = transaction.TargetWalletId
            });
        }

        [HttpPost]
        public IActionResult MakeTransfer(TransactionViewModel transaction)
        {
            transactionWebService.MakeTransfer(transaction);
            return RedirectToAction("Details", "Wallet", new
            {
                id = transaction.SourceWalletId
            });
        }

        [HttpGet]
        public IActionResult Update(int id, int transactionId)
        {
            var updatedTransaction = transactionWebService.Get(id, transactionId);
            return View(updatedTransaction);
        }

        [HttpPost]
        public IActionResult Update(int id, TransactionViewModel transaction)
        {
            if (ModelState.IsValid)
            {
                transactionWebService.Update(id, transaction);
            }
            return RedirectToAction("Details", "Wallet", new { id = transaction.Id });
        }

        [HttpGet]
        public IActionResult SetInitialBalance(int id)
        {
            var wallet = walletWebService.Get(id);
            var transaction = new TransactionViewModel
            {

                SourceWalletId = (int)wallet.Id,
                SourceWallet = wallet.Description
            };
            return View(transaction);
        }

        [HttpPost]
        public IActionResult SetInitialBalance(TransactionViewModel transaction)
        {
            transactionWebService.SetInitialBalance(transaction);
            return RedirectToAction("Details", "Wallet", new
            {
                id = transaction.SourceWalletId
            });
        }
    }
}

FamilyAccounting.Web/Views/Transaction/Details.cshtml
@model FamilyAccounting.Web.Models.TransactionViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Transaction @Model.Description</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Transaction ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            Amount
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2" style="display:none">
            @Html.DisplayNameFor(model => model.SourceWalletId)
        </dt>
        <dd class="col-sm-10" style="display:none">
            @Html.DisplayFor(model => model.SourceWalletId)
        </dd>
        <dt class="col-sm-2">
            From wallet
        </dt>
        <dd class="col-sm-10">
            <a asp-action="Details" asp-controller="Wallet" asp-route-id=@Model.SourceWalletId>@Html.DisplayFor(model => model.SourceWallet)</a>
        </dd>
        <dt class="col-sm-2" style="display:none">
            @Html.DisplayNameFor(model => model.TargetWalletId)
        </dt>
        <dd class="col-sm-10" style="display:none">
            @Html.DisplayFor(model => model.TargetWalletId)
        </dd>
        <dt class="col-sm-2">
            To wallet
        </dt>
        <dd class="col-sm-10">
            <a asp-action="Details" asp-controller="Wallet" asp-route-id=@Model.TargetWalletId>@Html.DisplayFor(model => model.TargetWallet)</a>
        </dd>
        <dt class="col-sm-2">
            Balance Before
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BalanceBefore)
        </dd>
        <dt class="col-sm-2">
            Balance After
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BalanceAfter)
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Date
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
        <dt class="col-sm-2" style="display:none">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class="col-sm-10" style="display:none">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            Status
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            Transaction Type
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TransactionType)
        </dd>
    </dl>
</div>
<div>
    @if (Model.TargetWalletId == 0 && Model.SourceWalletId != 0)
    {
        <a asp-action="Details" asp-controller="Wallet" asp-route-id="@Model.SourceWalletId">Back to Wallet</a>
    }
    else if (Model.SourceWalletId == 0 && Model.TargetWalletId != 0)
    {
        <a asp-action="Details" asp-controller="Wallet" asp-route-id="@Model.TargetWalletId">Back to Wallet</a>
    }
    else if (Model.SourceWalletId != 0 && Model.TargetWalletId != 0)
    {
        <a asp-action="Details" asp-controller="Wallet" asp-route-id="@Model.TargetWalletId">Back to Target Wallet</a> <span>|</span>
        <a asp-action="Details" asp-controller="Wallet" asp-route-id="@Model.SourceWalletId">Back to Source Wallet</a>
    }
    else
    {
        @*<a asp-action="Details" asp-controller="Wallet" asp-route-id="@Model.TargetWalletId">Back to Wallet</a>*@
    }
</div>

FamilyAccounting.Web/Views/Transaction/MakeExpense.cshtml
@model FamilyAccounting.Web.Models.TransactionViewModel

@{
    ViewData["Title"] = "Make expense";
}

<h1>Make expense</h1>

<div>
    <form method="post" asp-controller="Transaction" asp-action="MakeExpense">
        <input placeholder="Enter id of a source wallet" style="display:none" asp-for="SourceWalletId" />
        <div class="d-flex justify-content-between" style="margin-bottom:20px">
            <input style="margin-right:20px" class="form-control" placeholder="Describe the expense" asp-for="Description" />
            <input style="margin-right:20px" class="form-control" placeholder="Enter amount" asp-for="Amount" />
            <select asp-for="CategoryId" class="form-control">
                @foreach (var s in ViewBag.Categories)
                {
                    <option value="@s.Id">@s.Description</option>
                }
            </select>
        </div>
        <button class="btn btn-primary" type="submit" asp-controller="Transaction" asp-action="MakeExpense">
            Make expense
        </button>
        <button class="btn btn-info" asp-controller="Wallet" asp-action="Details" asp-route-id="@Model.SourceWalletId">Back to wallet</button>
    </form>
</div>

FamilyAccounting.Web/Views/Transaction/MakeIncome.cshtml
@model FamilyAccounting.Web.Models.TransactionViewModel

@{
    ViewData["Title"] = "Make icome";
}

<h1>Make income</h1>

<div>
    <form method="post" asp-controller="Transaction" asp-action="MakeIncome">
        <input placeholder="Enter id of a target wallet" style="display:none" asp-for="TargetWalletId" />
        <div class="d-flex justify-content-between" style="margin-bottom:20px">
            <input style="margin-right:20px" class="form-control" placeholder="Describe the income" asp-for="Description" />
            <input style="margin-right:20px" class="form-control" placeholder="Enter amount" asp-for="Amount" />
            <select asp-for="CategoryId" class="form-control">
                @foreach (var s in ViewBag.Categories)
                {
                    <option value="@s.Id">@s.Description</option>
                }
            </select>
        </div>
        <button class="btn btn-primary" type="submit" asp-controller="Transaction" asp-action="MakeIncome">
            Make income
        </button>
        <button class="btn btn-info" asp-controller="Wallet" asp-action="Details" asp-route-id="@Model.TargetWalletId">Back to wallet</button>
    </form>
</div>

FamilyAccounting.Web/Views/Transaction/MakeTransfer.cshtml
@model FamilyAccounting.Web.Models.TransactionViewModel

@{
    ViewData["Title"] = "Make transfer";
}

<h1>Make transfer</h1>

<div>
    <form method="post" asp-controller="Transaction" asp-action="MakeTransfer">
        <input placeholder="Enter id of a source wallet" style="display:none" asp-for="SourceWalletId" />
        <div class="d-flex justify-content-between" style="margin-bottom:20px">
            <select style="margin-right:20px" asp-for="TargetWalletId" class="form-control">
                @foreach (var s in ViewBag.Wallets)
                {
                    <option value="@s.Id">@s.Description</option>
                }
            </select>
            <input style="margin-right:20px" class="form-control" placeholder="Describe the transfer" asp-for="Description" />
            <input class="form-control" placeholder="Enter amount" asp-for="Amount" />
        </div>
        <button class="btn btn-primary" type="submit" asp-controller="Transaction" asp-action="MakeTransfer">
            Make transfer
        </button>
        <button class="btn btn-info" asp-controller="Wallet" asp-action="Details" asp-route-id="@Model.SourceWalletId">Back to wallet</button>
    </form>
</div>

FamilyAccounting.Web/Views/Transaction/SetInitialBalance.cshtml
@model FamilyAccounting.Web.Models.TransactionViewModel

@{
    ViewData["Title"] = "Set initial balance";
}

<h1>Set initial balance</h1>

<div>
    <form method="post" asp-controller="Transaction" asp-action="MakeExpense">
        <input placeholder="Enter id of a source wallet" style="display:none" asp-for="SourceWalletId" />
        <input style="margin-bottom:20px; width:300px;" class="form-control" placeholder="Enter amount" asp-for="Amount" />
        <button class="btn btn-primary" type="submit" asp-controller="Transaction" asp-action="SetInitialBalance">
            Set initial balance
        </button>
        <button class="btn btn-info" asp-controller="Wallet" asp-action="Details" asp-route-id="@Model.SourceWalletId">Back to wallet</button>
    </form>
</div>

FamilyAccounting.Web/Views/Transaction/Update.cshtml
@model FamilyAccounting.Web.Models.TransactionViewModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Wallet" asp-action="Details">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}